site_name: Tensing Mobile Client
site_url: https://kun-guru.github.io
extra:
  generator: false
theme:
  name: material
  features:
    - navigation.footer
docs_dir: docs

nav:
  - Navigation: 
    - Home: 
      - Shortcuts: Navigation/Home/shortcuts.md
      - Favorites: Navigation/Home/favorites.md
      - Dashboards: Navigation/Home/dashboards.md
      - Widgets: Navigation/Home/widgets.md
    - Inbox: Navigation/inbox.md
    - Map: Navigation/map.md
    - Time Keeping: Navigation/time_keeping.md
    - Print: Navigation/print.md
    - Print Queue: Navigation/print/queue.md
    - Bluetooth: Navigation/bluetooth.md
    - Help: Navigation/help.md
    - Exit: Navigation/exit.md
  - General:
    - Documents: General/Documents/documents.md
    - Switch Role : General/Switch Role/switch_role.md
    - Preferences : General/Preferences/preferences.md
  - Timekeeping : Timekeeping/timekeeping.md
  - Work Management : Work Management/work_management.md
  - Map View : Map View/map_view.md
  - Map Tools : Map Tools/map_tools.md
  - Map Redlines : Map Redlines/map_redlines.md 
  - Location : Location/location.md


